//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordertable
    {
        public decimal OID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<decimal> CUSTOMER_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    }
}
